version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install pytest
      #      pip install pytest flake8 bandit
      - save_cache:
          paths:
            - ~/.cache/pip
          key: v1-deps-{{ checksum "requirements.txt" }}
      # - run:
      #     name: Run linting
      #     command: flake8 .
      # - run:
      #     name: Run security checks
      #     command: bandit -r .
      - run:
          name: Run unit tests
          command: pytest tests/

workflows:
  version: 2
  test-workflow:
    jobs:
      - test